# Copyright 2025 yeeaiclub
#
# SPDX-License-Identifier: GPL-3.0-only

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly