// Code generated from oh-my-pi theme.ts; nerd/ascii maps use explicit \u/\U escapes (ASCII source).
//go:generate echo "regenerate: fetch packages/coding-agent/src/modes/theme/theme.ts and run tools/gen_symbol_presets.py"

package style

// SpinnerType selects spinner animation sets.
type SpinnerType string

const (
	SpinnerStatus   SpinnerType = "status"
	SpinnerActivity SpinnerType = "activity"
)

var nerdSymbolMap = map[string]string{
	"status.success": "\uf00c",
	"status.error": "\uf00d",
	"status.warning": "\uf12a",
	"status.info": "\uf129",
	"status.pending": "\uf254",
	"status.disabled": "\uf05e",
	"status.enabled": "\uf111",
	"status.running": "\uf110",
	"status.shadowed": "\u25d0",
	"status.aborted": "\uf04d",
	"nav.cursor": "\uf054",
	"nav.selected": "\uf178",
	"nav.expand": "\uf0da",
	"nav.collapse": "\uf0d7",
	"nav.back": "\uf060",
	"tree.branch": "\u251c\u2500",
	"tree.last": "\u2514\u2500",
	"tree.vertical": "\u2502",
	"tree.horizontal": "\u2500",
	"tree.hook": "\u2514",
	"boxRound.topLeft": "\u256d",
	"boxRound.topRight": "\u256e",
	"boxRound.bottomLeft": "\u2570",
	"boxRound.bottomRight": "\u256f",
	"boxRound.horizontal": "\u2500",
	"boxRound.vertical": "\u2502",
	"boxSharp.topLeft": "\u250c",
	"boxSharp.topRight": "\u2510",
	"boxSharp.bottomLeft": "\u2514",
	"boxSharp.bottomRight": "\u2518",
	"boxSharp.horizontal": "\u2500",
	"boxSharp.vertical": "\u2502",
	"boxSharp.cross": "\u253c",
	"boxSharp.teeDown": "\u252c",
	"boxSharp.teeUp": "\u2534",
	"boxSharp.teeRight": "\u251c",
	"boxSharp.teeLeft": "\u2524",
	"sep.powerline": "\ue0b0",
	"sep.powerlineThin": "\ue0b1",
	"sep.powerlineLeft": "\ue0b0",
	"sep.powerlineRight": "\ue0b2",
	"sep.powerlineThinLeft": "\ue0b1",
	"sep.powerlineThinRight": "\ue0b3",
	"sep.block": "\u2588",
	"sep.space": " ",
	"sep.asciiLeft": ">",
	"sep.asciiRight": "<",
	"sep.dot": " \u00b7 ",
	"sep.slash": "\ue0bb",
	"sep.pipe": "\ue0b3",
	"icon.model": "\uec19",
	"icon.plan": "\uf2d2",
	"icon.folder": "\uf115",
	"icon.file": "\uf15b",
	"icon.git": "\uf1d3",
	"icon.branch": "\uf126",
	"icon.pr": "\uea64",
	"icon.tokens": "\ue26b",
	"icon.context": "\ue70f",
	"icon.cost": "\uf155",
	"icon.time": "\uf017",
	"icon.pi": "\ue22c",
	"icon.agents": "\uf0c0",
	"icon.cache": "\uf1c0",
	"icon.input": "\uf090",
	"icon.output": "\uf08b",
	"icon.host": "\uf109",
	"icon.session": "\uf550",
	"icon.package": "\uf487",
	"icon.warning": "\uf071",
	"icon.rewind": "\uf0e2",
	"icon.auto": "\U000f0068",
	"icon.fast": "\uf0e7",
	"icon.extensionSkill": "\uf0eb",
	"icon.extensionTool": "\uf0ad",
	"icon.extensionSlashCommand": "\uf120",
	"icon.extensionMcp": "\uf1e6",
	"icon.extensionRule": "\uf0e3",
	"icon.extensionHook": "\uf0c1",
	"icon.extensionPrompt": "\uf075",
	"icon.extensionContextFile": "\uf0f6",
	"icon.extensionInstruction": "\uf02d",
	"icon.mic": "\uf130",
	"thinking.minimal": "\uf0e7 min",
	"thinking.low": "\uf10c low",
	"thinking.medium": "\uf192 med",
	"thinking.high": "\uf111 high",
	"thinking.xhigh": "\uf06d xhi",
	"checkbox.checked": "\uf14a",
	"checkbox.unchecked": "\uf096",
	"format.bullet": "\uf111",
	"format.dash": "\u2013",
	"format.bracketLeft": "\u27e8",
	"format.bracketRight": "\u27e9",
	"md.quoteBorder": "\u2502",
	"md.hrChar": "\u2500",
	"md.bullet": "\uf111",
	"lang.default": "",
	"lang.typescript": "\ue628",
	"lang.javascript": "\ue60c",
	"lang.python": "\ue606",
	"lang.rust": "\ue7a8",
	"lang.go": "\ue627",
	"lang.java": "\ue738",
	"lang.c": "\ue61e",
	"lang.cpp": "\ue61d",
	"lang.csharp": "\ue7bc",
	"lang.ruby": "\ue791",
	"lang.php": "\ue608",
	"lang.swift": "\ue755",
	"lang.kotlin": "\ue634",
	"lang.shell": "\ue795",
	"lang.html": "\ue736",
	"lang.css": "\ue749",
	"lang.json": "\ue60b",
	"lang.yaml": "\ue615",
	"lang.markdown": "\ue609",
	"lang.sql": "\ue706",
	"lang.docker": "\ue7b0",
	"lang.lua": "\ue620",
	"lang.text": "\ue612",
	"lang.env": "\ue615",
	"lang.toml": "\ue615",
	"lang.xml": "\U000f05c0",
	"lang.ini": "\ue615",
	"lang.conf": "\ue615",
	"lang.log": "\U000f0331",
	"lang.csv": "\U000f021b",
	"lang.tsv": "\U000f021b",
	"lang.image": "\U000f021f",
	"lang.pdf": "\U000f0226",
	"lang.archive": "\uf187",
	"lang.binary": "\U000f019a",
	"tab.appearance": "\U000f00e3",
	"tab.model": "\U000f06a9",
	"tab.interaction": "\U000f030c",
	"tab.context": "\U000f0638",
	"tab.editing": "\uebca",
	"tab.tools": "\U000f082d",
	"tab.tasks": "\U000f0431",
	"tab.providers": "\U000f059f",
}

var asciiSymbolMap = map[string]string{
	"status.success": "[ok]",
	"status.error": "[!!]",
	"status.warning": "[!]",
	"status.info": "[i]",
	"status.pending": "[*]",
	"status.disabled": "[ ]",
	"status.enabled": "[x]",
	"status.running": "[~]",
	"status.shadowed": "[/]",
	"status.aborted": "[-]",
	"nav.cursor": ">",
	"nav.selected": "->",
	"nav.expand": "+",
	"nav.collapse": "-",
	"nav.back": "<-",
	"tree.branch": "|--",
	"tree.last": "'--",
	"tree.vertical": "|",
	"tree.horizontal": "-",
	"tree.hook": "`-",
	"boxRound.topLeft": "+",
	"boxRound.topRight": "+",
	"boxRound.bottomLeft": "+",
	"boxRound.bottomRight": "+",
	"boxRound.horizontal": "-",
	"boxRound.vertical": "|",
	"boxSharp.topLeft": "+",
	"boxSharp.topRight": "+",
	"boxSharp.bottomLeft": "+",
	"boxSharp.bottomRight": "+",
	"boxSharp.horizontal": "-",
	"boxSharp.vertical": "|",
	"boxSharp.cross": "+",
	"boxSharp.teeDown": "+",
	"boxSharp.teeUp": "+",
	"boxSharp.teeRight": "+",
	"boxSharp.teeLeft": "+",
	"sep.powerline": ">",
	"sep.powerlineThin": ">",
	"sep.powerlineLeft": ">",
	"sep.powerlineRight": "<",
	"sep.powerlineThinLeft": ">",
	"sep.powerlineThinRight": "<",
	"sep.block": "#",
	"sep.space": " ",
	"sep.asciiLeft": ">",
	"sep.asciiRight": "<",
	"sep.dot": " - ",
	"sep.slash": " / ",
	"sep.pipe": " | ",
	"icon.model": "[M]",
	"icon.plan": "plan",
	"icon.folder": "[D]",
	"icon.file": "[F]",
	"icon.git": "git:",
	"icon.branch": "@",
	"icon.pr": "PR",
	"icon.tokens": "tok:",
	"icon.context": "ctx:",
	"icon.cost": "$",
	"icon.time": "t:",
	"icon.pi": "pi",
	"icon.agents": "AG",
	"icon.cache": "cache",
	"icon.input": "in:",
	"icon.output": "out:",
	"icon.host": "host",
	"icon.session": "id",
	"icon.package": "[P]",
	"icon.warning": "[!]",
	"icon.rewind": "<-",
	"icon.auto": "[A]",
	"icon.fast": ">>",
	"icon.extensionSkill": "SK",
	"icon.extensionTool": "TL",
	"icon.extensionSlashCommand": "/",
	"icon.extensionMcp": "MCP",
	"icon.extensionRule": "RL",
	"icon.extensionHook": "HK",
	"icon.extensionPrompt": "PR",
	"icon.extensionContextFile": "CF",
	"icon.extensionInstruction": "IN",
	"icon.mic": "MIC",
	"thinking.minimal": "[min]",
	"thinking.low": "[low]",
	"thinking.medium": "[med]",
	"thinking.high": "[high]",
	"thinking.xhigh": "[xhi]",
	"checkbox.checked": "[x]",
	"checkbox.unchecked": "[ ]",
	"format.bullet": "*",
	"format.dash": "-",
	"format.bracketLeft": "[",
	"format.bracketRight": "]",
	"md.quoteBorder": "|",
	"md.hrChar": "-",
	"md.bullet": "*",
	"lang.default": "code",
	"lang.typescript": "ts",
	"lang.javascript": "js",
	"lang.python": "py",
	"lang.rust": "rs",
	"lang.go": "go",
	"lang.java": "java",
	"lang.c": "c",
	"lang.cpp": "cpp",
	"lang.csharp": "cs",
	"lang.ruby": "rb",
	"lang.php": "php",
	"lang.swift": "swift",
	"lang.kotlin": "kt",
	"lang.shell": "sh",
	"lang.html": "html",
	"lang.css": "css",
	"lang.json": "json",
	"lang.yaml": "yaml",
	"lang.markdown": "md",
	"lang.sql": "sql",
	"lang.docker": "docker",
	"lang.lua": "lua",
	"lang.text": "txt",
	"lang.env": "env",
	"lang.toml": "toml",
	"lang.xml": "xml",
	"lang.ini": "ini",
	"lang.conf": "conf",
	"lang.log": "log",
	"lang.csv": "csv",
	"lang.tsv": "tsv",
	"lang.image": "img",
	"lang.pdf": "pdf",
	"lang.archive": "zip",
	"lang.binary": "bin",
	"tab.appearance": "[A]",
	"tab.model": "[M]",
	"tab.interaction": "[I]",
	"tab.context": "[X]",
	"tab.editing": "[E]",
	"tab.tools": "[T]",
	"tab.tasks": "[K]",
	"tab.providers": "[P]",
}

var spinnerFrames = map[SymbolPreset]map[SpinnerType][]string{
	SymbolPresetUnicode: {
		SpinnerStatus:   []string{"\u28fe", "\u28fd", "\u28fb", "\u28bf", "\u287f", "\u28df", "\u28ef", "\u28f7"},
		SpinnerActivity: []string{"\u280b", "\u2819", "\u2839", "\u2838", "\u283c", "\u2834", "\u2826", "\u2827", "\u2807", "\u280f"},
	},
	SymbolPresetNerd: {
		SpinnerStatus:   []string{"\U000f1456", "\U000f144b", "\U000f144c", "\U000f144d", "\U000f144e", "\U000f144f", "\U000f1450", "\U000f1451", "\U000f1452", "\U000f1453", "\U000f1454", "\U000f1455"},
		SpinnerActivity: []string{"\u280b", "\u2819", "\u2839", "\u2838", "\u283c", "\u2834", "\u2826", "\u2827", "\u2807", "\u280f"},
	},
	SymbolPresetAscii: {
		SpinnerStatus:   []string{"|", "/", "-", "\\"},
		SpinnerActivity: []string{"-", "\\", "|", "/"},
	},
}
